### ISSUE TITLE
Removed treasure.

### ISSUE THREAD

**Issue by Cluuey** [kemayo/wow-handynotes-treasurehunter#1]
Hi,
Like many of us I've been going through updating addons, I've even tried to sort out some bugs on some too but I'm not as cluey as I need to be.

I noticed a treasure marked on my map in an old zone, I thought I'd got them all but it was marked so I went out to it but it wasn't there. I did a Wowhead search and it seems I'm not the only one who's noticed this.
These images in these two links look remarkably similar and they both have the correct name but not all the data is there as a zone isn't connected to them.
https://www.wowhead.com/object=227742/sunken-treasure
https://www.wowhead.com/object=227615/sunken-treasure#comments

I've just right-clicked it and told it to hide but I thought I'd let you know so you could consider removing it. :-)

**Comment by kemayo** [comment]
Thanks for pointing that one out. I shall hide it.
