### ISSUE TITLE
RegisterPoints error.

### ISSUE THREAD

**Issue by Meebsy** [kemayo/wow-handynotes-treasurehunter#2]
`1x ...eHandyNotes_TreasureHunter\zones\Talador.lua:3: attempt to call field 'RegisterPoints' (a nil value)
[string "@HandyNotes_TreasureHunter\zones\Talador.lua"]:3: in main chunk`
The above error occured for each Draenor zone.

`1x HandyNotes_TreasureHunter\handler.lua:18: attempt to concatenate global 'ANIMA' (a nil value)
[string "@HandyNotes_TreasureHunter\handler.lua"]:18: in main chunk`

This error occured while in my covenant and I have no Idea how it was produced, throught I'd post it for you in case you know what it is talking about.

**Comment by kemayo** [comment]
Should have been fixed by 504768cc558acd5bcf64e61d0742881f12da4ac0.
