### ISSUE TITLE
Bug: Mousing over the "group" option on WM drop down

### ISSUE THREAD

**Issue by nancikennedy** [kemayo/wow-handynotes-treasurehunter#4]
On Retail, with the latest (alpha) version installed, when mousing over the "Group" submenu in the world map drop down list the following error occurs:

Message: ...AddOns/HandyNotes_TreasureHunter/handler/overlay.lua:16: attempt to compare two boolean values
Time: Sat Nov 19 20:58:08 2022
Count: 2
Stack: ...AddOns/HandyNotes_TreasureHunter/handler/overlay.lua:16: attempt to compare two boolean values
[string "@Interface/AddOns/HandyNotes_TreasureHunter/handler/overlay.lua"]:16: in function <...AddOns/HandyNotes_TreasureHunter/handler/overlay.lua:16>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/HandyNotes_TreasureHunter/handler/overlay.lua"]:22: in function <...AddOns/HandyNotes_TreasureHunter/handler/overlay.lua:17>
[string "@Interface/AddOns/HandyNotes_TreasureHunter/handler/overlay.lua"]:432: in function `InitializeDropDown'
[string "@Interface/AddOns/HandyNotes_TreasureHunter/handler/overlay.lua"]:454: in function `initFunction'
[string "@Interface/AddOns/HandyNotes_TreasureHunter/lib/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:756: in function `UIDropDownMenu_Initialize'
[string "@Interface/AddOns/HandyNotes_TreasureHunter/lib/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1742: in function `ToggleDropDownMenu'
[string "@Interface/AddOns/HandyNotes_TreasureHunter/lib/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:133: in function <...reHunter/lib/LibUIDropDownMenu/LibUIDropDownMenu.lua:128>
[string "@Interface/AddOns/HandyNotes_TreasureHunter/lib/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:436: in function <...reHunter/lib/LibUIDropDownMenu/LibUIDropDownMenu.lua:435>

Locals: a = true
b = true
(*temporary) = nil
(*temporary) = "attempt to compare two boolean values"

**Comment by kemayo** [comment]
Okay, fixed as of af2dc084d62a19e75cfd8603bac19fe8228a55ce -- technically the error had been there for ages, but the commit earlier that added the ever-shifting mirror portals was the first time that the right combination of situations lined up to actually trigger it.
