### ISSUE TITLE
Huge Lagspike when hovering over portals on map

### ISSUE THREAD

**Issue by highbot-core** [kemayo/wow-handynotes-treasurehunter#5]
Hi Kemayo,

first of all, huge thanks for all your map addon, really really helpfull.

I get a huge lagspike, when opening the map and hovering over the portals shown. Around 5-10 seconds.
I disabled all my addons expect Handynotes and this here.
Still lagspike.
Maybe you can take a look

**Comment by kemayo** [comment]
Huh, that's interesting -- it doesn't happen to me. Does it happen with any of the other nodes, or just the Ever-shifting mirror portals? Does your character have the Ever-shifting mirror toy, also?

Also, does it still happen if you disable the "use item tooltips" setting? 
![image](https://user-images.githubusercontent.com/2187/202920702-f822166f-f274-4c73-82a0-ccff4f9f324c.png)

**Comment by TinyTrbl** [comment]
I have like 20 sec of total game freeze if i move mouse over "portals" - even 3D stops rendering and i just have one static image.

For me it is related to Ever-Shifting Mirror (i don't have this toy, so maybe it is the main reason for these freezes?) - if i uncheck this option then these portals are gone and i have no freezes! :)

To get rid of freezes i can also uncheck Show Show Inaccessible as it will also hide these portals.

**Comment by kemayo** [comment]
@TinyTrbl same question for you about whether unchecking the "show item tooltips" option affects this, then. :D

**Comment by kemayo** [comment]
Well, I decided to switch it to completely hide the portals if you don't have the toy anyway. I'm still interested in that tooltip option if anyone checks it before updating addons, but this is probably a better experience for people who don't have the toy regardless...

**Comment by TinyTrbl** [comment]
> @TinyTrbl same question for you about whether unchecking the "show item tooltips" option affects this, then. :D

Oh, I forgot to mention this. Yes, I tried hovering over portals without tooltips and still got a freeze.
Love you Handynote addons but i am too cheap to donate! 😄

**Comment by kemayo** [comment]
Good to know about the option, thanks!
